"""Streamlit demo for the Bayesian sentiment analyzer.

Compatible with the JSON generated by extract_examples_cuda_fixed.py.

Usage (from project root):
    streamlit run app/streamlit_app.py
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np
import streamlit as st
import torch

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

import pyro
from pyro.infer.autoguide import AutoNormal

from src.data.loader import Standardizer, load_bow, load_tfidf
from src.data.preprocessing import clean_text
from src.evaluation.uncertainty import decompose_mc
from src.models.bnn_moe import BayesianMoE, BayesianMoEConfig
from src.models.deterministic import DeterministicMLP
from src.models.mc_dropout import MCDropoutMLP
from src.models.slda import AmortizedSLDA

ALL_MODELS = ["deterministic", "mc_dropout", "bnn_base", "bnn_moe", "bnn_moe_hetero"]
MODELS_ROOT = Path("experiments/results/models")
SLDA_DIR = Path("experiments/results/slda")
METRICS_RAW = Path("experiments/results/evaluation/metrics_raw.csv")
EXAMPLES_PATH = Path("experiments/results/example_reviews.json")

if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
elif getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
else:
    DEVICE = torch.device("cpu")


# -----------------------------
# Seed selection helpers
# -----------------------------

def _available_seeds(model_dir: Path) -> list[str]:
    return sorted([s.name for s in model_dir.iterdir() if s.is_dir() and s.name.startswith("seed_")])


def _best_seed(model_name: str) -> str | None:
    if not METRICS_RAW.exists():
        return None
    try:
        import csv
        best_seed, best_acc = None, -1.0
        with open(METRICS_RAW, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                if row["model"] == model_name and row["split"] == "test":
                    acc = float(row["accuracy"])
                    if acc > best_acc:
                        best_acc = acc
                        best_seed = f"seed_{row['seed']}"
        return best_seed
    except Exception:
        return None


def _available_models() -> list[str]:
    if not MODELS_ROOT.exists():
        return []
    return [
        n for n in ALL_MODELS
        if (MODELS_ROOT / n).exists() and _available_seeds(MODELS_ROOT / n)
    ]


# -----------------------------
# Load artifacts
# -----------------------------

@st.cache_resource
def load_bert(device_str: str):
    from transformers import DistilBertModel, DistilBertTokenizer

    device = torch.device(device_str)
    tok = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
    model = DistilBertModel.from_pretrained("distilbert-base-uncased")
    model.eval()
    model.to(device)
    return tok, model


def _slda_vectorizer_type() -> str:
    meta_path = SLDA_DIR / "slda_meta.json"
    if meta_path.exists():
        with open(meta_path, encoding="utf-8") as f:
            return json.load(f).get("vectorizer", "bow")
    if (SLDA_DIR / "lda.pkl").exists():
        return "bow"
    return "bow"


@st.cache_resource
def load_slda():
    if not (SLDA_DIR / "lda.pkl").exists():
        return None, None
    slda = AmortizedSLDA.load(SLDA_DIR, device="cpu")
    vec_type = _slda_vectorizer_type()
    if vec_type == "tfidf":
        _, vec = load_tfidf()
    else:
        _, vec = load_bow()
    return slda, vec


@st.cache_resource
def load_model(name: str, seed_name: str, device_str: str):
    device = torch.device(device_str)
    seed_dir = MODELS_ROOT / name / seed_name
    if not seed_dir.exists():
        return None

    if name in ("deterministic", "mc_dropout"):
        ck = torch.load(seed_dir / "state.pt", map_location="cpu", weights_only=False)
        input_dim = ck["input_dim"]
        if name == "deterministic":
            model = DeterministicMLP(input_dim=input_dim)
        else:
            model = MCDropoutMLP(input_dim=input_dim, dropout_p=ck.get("dropout_p", 0.2))
        model.load_state_dict(ck["state"])
        model.eval()
        model.to(device)
        scaler = Standardizer(ck["scaler_mean"], ck["scaler_std"])
        return {
            "name": name,
            "seed": seed_name,
            "kind": name,
            "model": model,
            "guide": None,
            "scaler": scaler,
            "use_theta": False,
            "device": device,
        }

    meta = torch.load(seed_dir / "meta.pt", map_location="cpu", weights_only=False)
    cfg = BayesianMoEConfig(**meta["cfg"])
    pyro.clear_param_store()
    state = torch.load(seed_dir / "pyro_store.pt", map_location=device, weights_only=False)
    pyro.get_param_store().set_state(state)
    model = BayesianMoE(cfg)
    model.to(device)
    guide = AutoNormal(model)
    dummy_x = torch.zeros(2, cfg.input_dim, device=device)
    dummy_y = torch.zeros(2, dtype=torch.long, device=device)
    if meta["use_theta"]:
        dummy_th = torch.ones(2, cfg.n_experts, device=device) / cfg.n_experts
        guide(dummy_x, dummy_th, dummy_y)
    else:
        guide(dummy_x, None, dummy_y)
    scaler = Standardizer(meta["scaler_mean"], meta["scaler_std"])
    param_snapshot = {k: v.detach().clone() for k, v in pyro.get_param_store().items()}
    return {
        "name": name,
        "seed": seed_name,
        "kind": "bnn",
        "model": model,
        "guide": guide,
        "scaler": scaler,
        "use_theta": bool(meta["use_theta"]),
        "cfg": cfg,
        "device": device,
        "_param_snapshot": param_snapshot,
    }


# -----------------------------
# Inference
# -----------------------------

def encode_text(text: str, tok, bert, device: torch.device) -> np.ndarray:
    text = clean_text(text)
    if not text.strip():
        text = "[UNK]"
    enc = tok([text], truncation=True, padding=True, max_length=256, return_tensors="pt")
    enc = {k: v.to(device) for k, v in enc.items()}
    with torch.inference_mode():
        h = bert(**enc).last_hidden_state[:, 0, :]
    return h.detach().cpu().float().numpy()


def theta_for_text(text: str, slda, vec) -> np.ndarray | None:
    if slda is None or vec is None:
        return None
    cleaned = clean_text(text) or "[UNK]"
    X = vec.transform([cleaned])
    return slda.theta(X)


def predict(
    text: str,
    bundle: dict,
    tok,
    bert,
    slda=None,
    vec=None,
    mc_samples: int = 20,
    precomputed_emb: np.ndarray | None = None,
    precomputed_theta: np.ndarray | None = None,
):
    device = bundle["device"]
    emb = precomputed_emb if precomputed_emb is not None else encode_text(text, tok, bert, device)
    emb = np.asarray(emb, dtype=np.float32)
    if emb.ndim == 1:
        emb = emb[np.newaxis, :]

    emb_t_cpu = torch.tensor(emb, dtype=torch.float32)
    emb_std = bundle["scaler"].transform(emb_t_cpu).to(device)

    theta_np = None
    if bundle.get("use_theta"):
        if precomputed_theta is not None:
            theta_np = np.asarray(precomputed_theta, dtype=np.float32)
            if theta_np.ndim == 1:
                theta_np = theta_np[np.newaxis, :]
        else:
            theta_np = theta_for_text(text, slda, vec)
            if theta_np is None:
                n_exp = bundle["cfg"].n_experts
                theta_np = np.ones((1, n_exp), dtype=np.float32) / n_exp
        theta_t = torch.tensor(theta_np, dtype=torch.float32, device=device)
    else:
        theta_t = None

    if bundle["kind"] == "deterministic":
        with torch.inference_mode():
            probs = torch.softmax(bundle["model"](emb_std), dim=-1)
        mc = probs.unsqueeze(0)
    elif bundle["kind"] == "mc_dropout":
        with torch.inference_mode():
            logits = bundle["model"].mc_forward(emb_std, mc_samples=mc_samples)
            mc = torch.softmax(logits, dim=-1)
    else:
        if "_param_snapshot" in bundle:
            pyro.clear_param_store()
            for k, v in bundle["_param_snapshot"].items():
                pyro.get_param_store()[k] = v.detach().clone()
        predictive = pyro.infer.Predictive(
            bundle["model"],
            guide=bundle["guide"],
            num_samples=mc_samples,
            return_sites=("_RETURN",),
        )
        if theta_t is not None:
            logits = predictive(emb_std, theta_t)["_RETURN"]
        else:
            logits = predictive(emb_std)["_RETURN"]
        mc = torch.softmax(logits, dim=-1)

    decomp = decompose_mc(mc)
    return {
        "mean_probs": mc.mean(0).squeeze(0).detach().cpu().numpy(),
        "predictive_entropy": float(decomp["predictive_entropy"].item()),
        "aleatoric_entropy": float(decomp["aleatoric_entropy"].item()),
        "mutual_info": float(decomp["mutual_info"].item()),
        "theta": theta_np[0] if theta_np is not None else None,
        "mc_samples_count": int(mc.shape[0]),
    }


# -----------------------------
# Examples
# -----------------------------

def _load_examples() -> tuple[dict[str, str], dict[str, dict[str, Any]]]:
    options = {"— write your own —": ""}
    records: dict[str, dict[str, Any]] = {}
    if not EXAMPLES_PATH.exists():
        return options, records

    try:
        data = json.loads(EXAMPLES_PATH.read_text(encoding="utf-8"))
        for label_key, label_name in [("positive", "Positive"), ("negative", "Negative")]:
            for i, e in enumerate(data.get(label_key, []), 1):
                h = e.get("max_entropy", e.get("mean_entropy", 0.0))
                key = f"{label_name} example {i}  (worst H={h:.3f})"
                options[key] = e["text"]
                records[key] = e
    except Exception:
        pass
    return options, records


def _example_expected_label(example_record: dict[str, Any] | None) -> str | None:
    if example_record is None or "label" not in example_record:
        return None
    return "POSITIVE" if int(example_record["label"]) == 1 else "NEGATIVE"


# -----------------------------
# UI
# -----------------------------

st.set_page_config(page_title="Bayesian Sentiment", page_icon="🧠", layout="wide")
st.title("🧠 Bayesian Sentiment Analyzer")
st.caption("Monteagudo & Rey — MUIA 2025/2026 · IA Probabilística")
st.caption(f"Running on: {DEVICE}")

with st.sidebar:
    st.header("Model")
    available_models = _available_models()
    if not available_models:
        st.error("No trained models found. Run the training pipeline first.")
        st.stop()

    selected_model = st.selectbox("Architecture", available_models, index=0)

    seeds = _available_seeds(MODELS_ROOT / selected_model)
    best = _best_seed(selected_model)
    seed_options = ["Auto (best accuracy)"] + seeds
    seed_choice = st.selectbox("Seed", seed_options, index=0)

    if seed_choice == "Auto (best accuracy)":
        resolved_seed = best if best and best in seeds else seeds[0]
        if best:
            st.caption(f"Best seed by test accuracy: **{resolved_seed}**")
    else:
        resolved_seed = seed_choice

    bundle = load_model(selected_model, resolved_seed, str(DEVICE))
    if bundle is None:
        st.error(f"Could not load {selected_model} / {resolved_seed}")
        st.stop()

    bayesian = bundle["kind"] != "deterministic"
    st.info(f"Loaded: **{bundle['name']}** · {resolved_seed}")
    st.write(f"Bayesian: {bayesian} · Topic gating: {bundle.get('use_theta', False)}")

    st.divider()
    st.header("Sampling")
    default_mc = 20 if bayesian else 1
    mc_samples = st.slider("MC samples", 1, 100, default_mc, step=1)
    st.caption("More samples = more stable uncertainty, but slower.")

    st.divider()
    st.header("Decision rule")
    if bayesian:
        score_name = st.selectbox(
            "Uncertainty score for abstention",
            ["mutual_info", "predictive_entropy"],
            index=0,
        )
        max_tau = 0.693 if score_name == "predictive_entropy" else 0.35
        default_tau = 0.05 if score_name == "mutual_info" else 0.40
    else:
        score_name = "predictive_entropy"
        max_tau = 0.693
        default_tau = 0.40

    tau = st.slider("Rejection threshold τ", 0.0, float(max_tau), float(default_tau), step=0.005)
    st.caption("Higher τ → model abstains less often")

    if bundle.get("use_theta"):
        vec_type = _slda_vectorizer_type()
        st.caption(f"sLDA vectorizer: **{vec_type}**")

tok, bert = load_bert(str(DEVICE))
slda, vec = load_slda() if bundle.get("use_theta") else (None, None)

example_options, example_records = _load_examples()
example_choice = st.selectbox("Predefined example", list(example_options.keys()), index=0)
selected_example = example_records.get(example_choice)
default_text = example_options[example_choice]
text = st.text_area(
    "Review text",
    value=default_text,
    height=180,
    placeholder="Paste a movie review here...",
)

if selected_example is not None:
    expected = _example_expected_label(selected_example)
    if expected is not None:
        st.caption(f"Expected label for this predefined example: **{expected}**")

if st.button("Analyze", type="primary"):
    use_precomputed = False
    pre_emb = None
    pre_theta = None
    if selected_example is not None and text.strip() == selected_example.get("text", "").strip():
        if "embedding" in selected_example:
            pre_emb = np.asarray(selected_example["embedding"], dtype=np.float32)
            pre_theta = np.asarray(selected_example["theta"], dtype=np.float32) if "theta" in selected_example else None
            use_precomputed = True

    with st.spinner("Running predictions..."):
        out = predict(
            text,
            bundle,
            tok,
            bert,
            slda=slda,
            vec=vec,
            mc_samples=mc_samples,
            precomputed_emb=pre_emb,
            precomputed_theta=pre_theta,
        )

    p_neg = float(out["mean_probs"][0])
    p_pos = float(out["mean_probs"][1])
    H = out["predictive_entropy"]
    H_ale = out["aleatoric_entropy"]
    MI = out["mutual_info"]
    score_value = MI if score_name == "mutual_info" else H

    decision = "🙋 ABSTAIN (human review)" if score_value > tau else ("😊 POSITIVE" if p_pos >= p_neg else "😞 NEGATIVE")

    st.subheader("Prediction")
    c1, c2, c3 = st.columns(3)
    c1.metric("p(negative)", f"{p_neg:.3f}")
    c2.metric("p(positive)", f"{p_pos:.3f}")
    c3.metric("Decision", decision)

    if use_precomputed:
        st.caption("Used cached embedding/theta from example_reviews.json for this predefined example.")
    elif selected_example is not None:
        st.caption("The text was edited or the example has no cached features, so it was re-encoded online.")

    if score_value > tau:
        st.warning(f"{score_name} = {score_value:.3f} > τ = {tau:.3f}. Routing to human review.")
    else:
        st.success(f"{score_name} = {score_value:.3f} ≤ τ = {tau:.3f}. Auto-classify.")

    st.subheader("Uncertainty")
    if bayesian:
        d1, d2, d3 = st.columns(3)
        d1.metric("Predictive entropy H[ȳ]", f"{H:.4f}")
        d2.metric("Aleatoric E[H(p)]", f"{H_ale:.4f}")
        d3.metric("Epistemic MI", f"{MI:.4f}")
    else:
        st.metric("Predictive entropy", f"{H:.4f}")
        st.caption("Deterministic model — no epistemic/aleatoric decomposition available.")

    if out["theta"] is not None:
        st.subheader("Topic mixture θ (sLDA)")
        try:
            with open(SLDA_DIR / "topic_words.json", encoding="utf-8") as f:
                tw = json.load(f)
            with open(SLDA_DIR / "topic_sentiment.json", encoding="utf-8") as f:
                ts = json.load(f)
        except Exception:
            tw, ts = {}, {}
        theta = out["theta"]
        top3 = np.argsort(theta)[::-1][:3]
        for k in top3:
            words = " ".join(tw.get(str(int(k)), [])[:8])
            sent = float(ts.get(str(int(k)), 0.0))
            tag = "POS" if sent > 0.1 else ("NEG" if sent < -0.1 else "neu")
            st.write(f"- **Topic {int(k)}** ({theta[k] * 100:.1f}%, {tag} {sent:+.2f}): _{words}_")

    with st.expander("Raw output"):
        st.json({
            "mean_probs": out["mean_probs"].tolist(),
            "predictive_entropy": H,
            "aleatoric_entropy": H_ale,
            "mutual_info": MI,
            "decision_score": score_name,
            "decision_value": score_value,
            "mc_samples": out["mc_samples_count"],
        })
